### ISSUE TITLE
Issues on launching a driving in Argoverse

### ISSUE THREAD

**Issue by rondey** [metadriverse/metadrive#103]
Hello, I have followed the documentation to launch a driving in Argoverse. The first issue was in `python -m metadrive.examples.drive_in_argoverse`: actually the module is named `metadrive.examples.drive_in_argoverse_env`.

The second issue happens using `python -m metadrive.examples.drive_in_argoverse_env`:

    Traceback (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/home/myuser/metadrive/metadrive/examples/drive_in_argoverse_env.py", line 9, in <module>
      o = env.reset()
    File "/home/myuser/metadrive/metadrive/envs/base_env.py", line 296, in reset
      self.engine.reset()
    File "/home/myuser/metadrive/metadrive/engine/base_engine.py", line 190, in reset
      manager.reset()
    File "/home/myuser/metadrive/metadrive/envs/argoverse_env.py", line 31, in reset
      map = ArgoverseMap(self.engine.global_config["map_config"])
    File "/home/myuser/metadrive/metadrive/component/map/argoverse_map.py", line 45, in __init__
      super(ArgoverseMap, self).__init__(map_config=map_config, random_seed=None)
    File "/home/myuser/metadrive/metadrive/component/map/base_map.py", line 89, in __init__
      self._generate()
    File "/home/myuser/metadrive/metadrive/component/map/argoverse_map.py", line 76, in _generate
      self._construct_road_network([lane_objs[k] for k in lane_ids])
    File "/home/myuser/metadrive/metadrive/component/map/argoverse_map.py", line 85, in _construct_road_network
      block.construct_block(self.engine.worldNP, self.engine.physics_world)
    File "/home/myuser/metadrive/metadrive/component/blocks/base_block.py", line 89, in construct_block
      success = self._sample_topology()
    File "/home/myuser/metadrive/metadrive/component/blocks/argoverse_block.py", line 20, in _sample_topology
      self.add_lanes()
    File "/home/myuser/metadrive/metadrive/component/blocks/argoverse_block.py", line 112, in add_lanes
      _, left_lat = self.argo_lanes[lane.l_neighbor_id].local_coordinates(lane.center_line_points[0])
    AttributeError: 'ArgoverseLane' object has no attribute 'center_line_points'

I supposed that the solution was simply to change 
`_, left_lat = self.argo_lanes[lane.l_neighbor_id].local_coordinates(lane.center_line_points[0])` 
in 
` _, left_lat = self.argo_lanes[lane.l_neighbor_id].local_coordinates(lane.centerline[0])`.

However, after this change a new error appeared:

            Traceback (most recent call last):
              File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
                return _run_code(code, main_globals, None,
              File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
                exec(code, run_globals)
              File "/home/myuser/metadrive/metadrive/examples/drive_in_argoverse_env.py", line 9, in <module>
                o = env.reset()
              File "/home/myuser/metadrive/metadrive/envs/base_env.py", line 296, in reset
                self.engine.reset()
              File "/home/myuser/metadrive/metadrive/engine/base_engine.py", line 190, in reset
                manager.reset()
              File "/home/myuser/metadrive/metadrive/manager/agent_manager.py", line 101, in reset
                init_vehicles = self._get_vehicles(config_dict=self.engine.global_config["target_vehicle_configs"])
              File "/home/myuser/metadrive/metadrive/manager/agent_manager.py", line 67, in _get_vehicles
                obj = self.spawn_object(v_type, vehicle_config=v_config)
              File "/home/myuser/metadrive/metadrive/manager/base_manager.py", line 66, in spawn_object
                object = self.engine.spawn_object(object_class, **kwargs)
              File "/home/myuser/metadrive/metadrive/engine/base_engine.py", line 103, in spawn_object
                obj = object_class(**kwargs)
              File "/home/myuser/metadrive/metadrive/component/vehicle/base_vehicle.py", line 194, in __init__
                self.reset()
              File "/home/myuser/metadrive/metadrive/component/vehicle/base_vehicle.py", line 306, in reset
                lane = map.road_network.get_lane(self.config["spawn_lane_index"])
              File "/home/myuser/metadrive/metadrive/component/road/road_network.py", line 177, in get_lane
                return self.graph[_from][_to][_id]
            KeyError: '>'

**Comment by SHITIANYU-hue** [comment]
Hi Quanyi, May I know if it is possible to support the Argoverse map now? Thanks!

**Comment by QuanyiLi** [comment]
> Hi Quanyi, May I know if it is possible to support the Argoverse map now? Thanks!

Actually, No.  We do not have enough budget on making the Argoverse environment compatible with the latest MetaDrive. It receives a lower priority now, since the number of Argoverse maps is limited (<100) and they don't contain enough information, like the lane width.
