### ISSUE TITLE
Topdown renderer is broken when using Waymo env

### ISSUE THREAD

**Issue by pengzhenghao** [metadriverse/metadrive#229]
```bash
Traceback (most recent call last):
  File "/home/zhenghao/drivingforce/drivingforce/newcopo/play_metadrive_real_data.py", line 39, in <module>
    env.render("topdown")
  File "/home/zhenghao/metadrive/metadrive/envs/base_env.py", line 302, in render
    return self._render_topdown(*args, **kwargs)
  File "/home/zhenghao/metadrive/metadrive/envs/base_env.py", line 524, in _render_topdown
    self._top_down_renderer = TopDownRenderer(*args, **kwargs)
  File "/home/zhenghao/metadrive/metadrive/obs/top_down_renderer.py", line 153, in __init__
    self.map, simple_draw=False, return_surface=True, film_size=film_size, road_color=road_color
  File "/home/zhenghao/metadrive/metadrive/obs/top_down_renderer.py", line 44, in draw_top_down_map
    for _to in map.road_network.graph[_from].keys():
AttributeError: 'neighbor_lanes' object has no attribute 'keys'
```

**Comment by pengzhenghao** [comment]
It is resolved.
