### ISSUE TITLE
Auto drive mode switch crash on windows

### ISSUE THREAD

**Issue by CarlDegio** [metadriverse/metadrive#295]
I meet a bug of auto drive mode switch. I press T and then the program crash:
```
python -m metadrive.examples.drive_in_single_agent_env
Successfully registered the following environments: ['MetaDrive-validation-v0', 'MetaDrive-10env-v0', 'MetaDrive-100envs-v0', 'MetaDrive-1000envs-v0', 'SafeMetaDrive-validation-v0', 'SafeMetaDrive-10env-v0', 'SafeMetaDrive-100envs-v0', 'SafeMetaDrive-1000envs-v0', 'MARLTollgate-v0', 'MARLBottleneck-v0', 'MARLRoundabout-v0', 'MARLIntersection-v0', 'MARLParkingLot-v0', 'MARLMetaDrive-v0'].
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
Keyboard Shortcuts:
  W: Acceleration
  S: Braking
  A: Moving Left
  D: Moving Right
  R: Reset the Environment
  H: Help Message
  F: Switch FPS to unlimited / realtime
  Q: Third-person View Camera
  B: Top-down View Camera (control: WASD-=)
  +: Lift Camera
  -: Lower Camera
  Mouse click: move camera (top-down view)
  Esc: Quit

The observation is an numpy array with shape:  (261,)
<------here I press T-------->
The expert takeover is set to:  False
Traceback (most recent call last):
  File "D:\program\miniconda3\envs\metadrive\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\program\miniconda3\envs\metadrive\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\PythonSpace\metadrive\metadrive\examples\drive_in_single_agent_env.py", line 56, in <module>
    raise e
  File "D:\PythonSpace\metadrive\metadrive\examples\drive_in_single_agent_env.py", line 46, in <module>
    o, r, d, info = env.step([0, 0])
  File "D:\PythonSpace\metadrive\metadrive\envs\base_env.py", line 267, in step
    engine_info = self._step_simulator(actions)
  File "D:\PythonSpace\metadrive\metadrive\envs\base_env.py", line 294, in _step_simulator
    scene_manager_before_step_infos = self.engine.before_step(actions)
  File "D:\PythonSpace\metadrive\metadrive\engine\base_engine.py", line 290, in before_step
    new_step_infos = manager.before_step()
  File "D:\PythonSpace\metadrive\metadrive\manager\agent_manager.py", line 229, in before_step
    action = policy.act(agent_id)
  File "D:\PythonSpace\metadrive\metadrive\policy\manual_control_policy.py", line 57, in act
    return self.controller.process_input(self.engine.current_track_vehicle)
  File "D:\PythonSpace\metadrive\metadrive\engine\core\manual_controller.py", line 78, in process_input
    return np.array([self.steering, self.throttle_brake], dtype=np.float64)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```
And press R(reset env) also crash.

Other key is ok, such as +/-/B/H/F. WASD can't test in auto mode so I can't test them.

**Comment by QuanyiLi** [comment]
Hummm, I can not reproduce it. What is your ```numpy``` version? and Do you change anything in that script?

**Comment by CarlDegio** [comment]
numpy version is 1.24.2, and I install metadrive just now so there are no change. Maybe I reinstall it

**Comment by CarlDegio** [comment]
I reinstall it but still crash. It report some dimension problems.

**Comment by CarlDegio** [comment]
I found this:
![image](https://user-images.githubusercontent.com/52379582/219665460-392b6197-85c5-4003-839d-96ea71c65c6b.png)
![image](https://user-images.githubusercontent.com/52379582/219665488-3e52cce5-0e41-44ec-b720-6e8fba41effb.png)

Actually, this two seems should be float without shape

**Comment by CarlDegio** [comment]
seems problem here: in metadrive\engine\core\manual_controller.py
![image](https://user-images.githubusercontent.com/52379582/219667866-c93f3684-862e-4717-bf7b-fd1e4c4221f0.png)
this rand lead to different shape.

**Comment by QuanyiLi** [comment]
Yes, I got it. The numpy-1.24.2 causes this. Already fixed it and merged to main branch.

**Comment by CarlDegio** [comment]
Thank you!
