### ISSUE TITLE
[Help Request] Uncompatible ray version lead to fail to run 'python3.8 train_generalization_experiment.py '

### ISSUE THREAD

**Issue by l1xiao** [metadriverse/metadrive#556]
Hi, I ran `python3.8 train_generalization_experiment.py ` but failed. Logs are following:
Traceback (most recent call last):
  File "train_generalization_experiment.py", line 16, in <module>
    from metadrive.envs.gym_wrapper import createGymWrapper
ImportError: cannot import name 'createGymWrapper' from 'metadrive.envs.gym_wrapper' (/home/xx/metadrive/metadrive/envs/gym_wrapper.py)

I tried other examples and all worked well.

System: Ubuntu 20.04
Commit:
commit 0df2f979e97e39282b3634a7984a2e20c77e4263 (HEAD -> main, origin/main, origin/HEAD)
Author: Quanyi Li <quanyili0057@gmail.com>
Date:   Tue Nov 14 00:47:35 2023 +0000
    Cleanup (#551)
    * rename return raw style
    * clean lanes
    * optimize sidewalk for PGMap
 
I modified as follow, 
![image](https://github.com/metadriverse/metadrive/assets/6694585/e2d91609-a611-4be5-8800-86363971f3af)
![image](https://github.com/metadriverse/metadrive/assets/6694585/60f1df95-ec43-4176-8fd7-269602773ea4)
and install ray==2.2.0. There is still has error:
/home/xx/metadrive/venv/bin/python /home/lixiao07/metadrive/metadrive/examples/train_generalization_experiment.py 

```
// ...Folded Status log...//
== Status ==
Current time: 2023-11-17 15:08:42 (running for 00:00:29.11)
Memory usage on this node: 25.0/62.7 GiB 
Using FIFO scheduling algorithm.
Resources requested: 14.999999999999982/16 CPUs, 0/0 GPUs, 0.0/18.13 GiB heap, 0.0/9.07 GiB objects (0.0/1.0 accelerator_type:G)
Result logdir: /home/xx/metadrive/metadrive/examples/generalization_experiment
Number of trials: 8/8 (2 PENDING, 6 RUNNING)
+-------------------------------+----------+-------+------------------------+------------------------+------------------------+
| Trial name                    | status   | loc   |   env_config/num_scena |   env_config/start_see |   env_config/traffic_d |
|                               |          |       |                   rios |                      d |                 ensity |
|-------------------------------+----------+-------+------------------------+------------------------+------------------------|
| PPO_GymEnvWrapper_128d0_00000 | RUNNING  |       |                      1 |                   5000 |                    0.1 |
| PPO_GymEnvWrapper_128d0_00001 | RUNNING  |       |                      3 |                   5000 |                    0.1 |
| PPO_GymEnvWrapper_128d0_00002 | RUNNING  |       |                      5 |                   5000 |                    0.1 |
| PPO_GymEnvWrapper_128d0_00003 | RUNNING  |       |                   1000 |                   5000 |                    0.1 |
| PPO_GymEnvWrapper_128d0_00004 | RUNNING  |       |                      1 |                   5000 |                    0.3 |
| PPO_GymEnvWrapper_128d0_00005 | RUNNING  |       |                      3 |                   5000 |                    0.3 |
| PPO_GymEnvWrapper_128d0_00006 | PENDING  |       |                      5 |                   5000 |                    0.3 |
| PPO_GymEnvWrapper_128d0_00007 | PENDING  |       |                   1000 |                   5000 |                    0.3 |
+-------------------------------+----------+-------+------------------------+------------------------+------------------------+

2023-11-17 15:08:48,205	ERROR trial_runner.py:1088 -- Trial PPO_GymEnvWrapper_128d0_00000: Error processing event.
ray.tune.error._TuneNoNextExecutorEventError: Traceback (most recent call last):
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/ray/tune/execution/ray_trial_executor.py", line 1070, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::PPO.__init__() (pid=439909, ip=11.2.151.105, repr=PPO)
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 441, in __init__
    super().__init__(
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 169, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 566, in setup
    self.workers = WorkerSet(
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 169, in __init__
    self._setup(
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 253, in _setup
    spaces = self._get_spaces_from_remote_worker()
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 279, in _get_spaces_from_remote_worker
    remote_spaces = self.foreach_worker(
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 696, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 73, in handle_remote_call_result_errors
    raise r.get()
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/ray/rllib/utils/actor_manager.py", line 473, in __fetch_result
    result = ray.get(r)
ray.exceptions.RaySystemError: System error: _generator_ctor() takes from 0 to 1 positional arguments but 2 were given
traceback: Traceback (most recent call last):
TypeError: _generator_ctor() takes from 0 to 1 positional arguments but 2 were given
```

**Comment by l1xiao** [comment]
I modified as follow, 
![image](https://github.com/metadriverse/metadrive/assets/6694585/e2d91609-a611-4be5-8800-86363971f3af)
![image](https://github.com/metadriverse/metadrive/assets/6694585/60f1df95-ec43-4176-8fd7-269602773ea4)
and install ray==1.2.0. There is still has error:
/home/xx/metadrive/venv/bin/python /home/lixiao07/metadrive/metadrive/examples/train_generalization_experiment.py 
```
Traceback (most recent call last):
  File "/home/xx/metadrive/metadrive/examples/train_generalization_experiment.py", line 19, in <module>
    import ray
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/ray/__init__.py", line 63, in <module>
    import ray._raylet  # noqa: E402
  File "python/ray/_raylet.pyx", line 102, in init ray._raylet
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/ray/exceptions.py", line 7, in <module>
    from ray.core.generated.common_pb2 import RayException, Language, PYTHON
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/ray/core/generated/common_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/xx/metadrive/venv/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 789, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

**Comment by QuanyiLi** [comment]
Please use `ray==1.0.0` or `ray=1.2.0` to run the experiments. As for the `gymWrapper` error, did you install `gym`, which should be the `openai.gym` instead of `gymnasium`?
