### ISSUE TITLE
KeyError: "'main_camera' does not exist in existing config.

### ISSUE THREAD

**Issue by rgu01** [metadriverse/metadrive#653]
OS: Linux Ubuntu 22.04.3 LTS
Processor: Intel® Core™ i5-8250U CPU @ 1.60GHz × 4
Graphics: llvmpipe (LLVM 15.0.7, 256 bits)
Virtual machine: Oracle VirtualBox Version 7.0.10 r158379
Issue: After strictly following the installation steps, running "python -m metadrive.examples.verify_headless_installation" generates the following the errors:

[INFO] Environment: MetaDriveEnv
[INFO] MetaDrive version: 0.4.2.3
[INFO] Sensors: [lidar: Lidar(), side_detector: SideDetector(), lane_line_detector: LaneLineDetector()]
[INFO] Render Mode: none
[INFO] Horizon (Max steps per agent): None
[INFO] Assets version: 0.4.2.3
[INFO] Known Pipes: glxGraphicsPipe
[INFO] Start Scenario Index: 0, Num Scenarios : 1
[INFO] Episode ended! Scenario Index: 0 Reason: out_of_road.
Bullet physics world is launched successfully!
[INFO] Environment: MetaDriveEnv
[INFO] MetaDrive version: 0.4.2.3
[INFO] Sensors: [lidar: Lidar(), side_detector: SideDetector(), lane_line_detector: LaneLineDetector(), rgb_camera: RGBCamera(256, 256), depth_camera: DepthCamera(256, 256)]
[INFO] Render Mode: offscreen
[INFO] Horizon (Max steps per agent): None
Traceback (most recent call last):
  File "/home/rgu01/miniconda3/envs/scenarionet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rgu01/miniconda3/envs/scenarionet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rgu01/MetaDrive/metadrive/metadrive/examples/verify_headless_installation.py", line 11, in <module>
    verify_installation(args.cuda, args.camera)
  File "/home/rgu01/MetaDrive/metadrive/metadrive/tests/test_installation.py", line 84, in verify_installation
    capture_headless_image(cuda)
  File "/home/rgu01/MetaDrive/metadrive/metadrive/tests/test_installation.py", line 14, in capture_headless_image
    env = MetaDriveEnv(
  File "/home/rgu01/MetaDrive/metadrive/metadrive/envs/metadrive_env.py", line 103, in __init__
    super(MetaDriveEnv, self).__init__(config)
  File "/home/rgu01/MetaDrive/metadrive/metadrive/envs/base_env.py", line 302, in __init__
    self.agent_manager = self._get_agent_manager()
  File "/home/rgu01/MetaDrive/metadrive/metadrive/envs/base_env.py", line 399, in _get_agent_manager
    return VehicleAgentManager(init_observations=self._get_observations())
  File "/home/rgu01/MetaDrive/metadrive/metadrive/envs/base_env.py", line 396, in _get_observations
    return {DEFAULT_AGENT: self.get_single_observation()}
  File "/home/rgu01/MetaDrive/metadrive/metadrive/envs/base_env.py", line 670, in get_single_observation
    o = ImageStateObservation(self.config) if img_obs else LidarStateObservation(self.config)
  File "/home/rgu01/MetaDrive/metadrive/metadrive/obs/image_obs.py", line 26, in __init__
    self.img_obs = ImageObservation(config, config["vehicle_config"]["image_source"], config["norm_pixel"])
  File "/home/rgu01/MetaDrive/metadrive/metadrive/obs/image_obs.py", line 61, in __init__
    self.state = np.zeros(self.observation_space.shape, dtype=np.float32 if self.norm_pixel else np.uint8)
  File "/home/rgu01/MetaDrive/metadrive/metadrive/obs/image_obs.py", line 67, in observation_space
    sensor_cls = self.config["sensors"][self.image_source][0]
  File "/home/rgu01/MetaDrive/metadrive/metadrive/utils/config.py", line 226, in __getitem__
    self._check_and_raise_key_error(item)
  File "/home/rgu01/MetaDrive/metadrive/metadrive/utils/config.py", line 212, in _check_and_raise_key_error
    raise KeyError(
KeyError: "'main_camera' does not exist in existing config. Please use config.update(...) to update the config. Existing keys: dict_keys(['lidar', 'side_detector', 'lane_line_detector', 'rgb_camera', 'depth_camera'])."

**Comment by QuanyiLi** [comment]
Thank you for reporting this. It seems our unitest is broken. Now it is fixed!
